baseURL = "https://cruisemaniac.com/"
languageCode = "en-us"
paginate = 6
summarylength = 10
title = "cruisemaniac | The cloud guy!"
theme = "blogge-hugo-theme"

[menu]
  [[menu.main]]
    name = "Home"
    url= ""
    weight= 1
  [[menu.main]]
    name = "About"
    url= "about"
    weight= 2
  [[menu.main]]
    name = "Contact"
    url= "contact"
    weight= 3
  [[menu.main]]
    name = "Projects & Talks"
    url= "projects-and-talks"
    weight= 3
[params]
  summarylength = 80
  logo = "images/logo.png"
  author = "Ashwin"
  authorThumb = "images/ashwin.jpg"
  authorAddress = "Abu Dhabi, UAE"
  authorPhone = "+971505659644"
  instaUsername = ""
  facebookUsername = ""
  twitterUsername = "cruisemaniac"
  linkedinUsername = "ashwinmurali"
  githubUsername = "cruisemaniac"
  blogTitle = "Posts"
  blogSubTitle = ""
  trendingBlogIcon = "images/blog/icon.svg"
  # Replace the third party URL/API with yours
  # We're using formspree.io for form handling, paste your formspree url below
  fabformURL  = "9AJk8ro"
  googleMapAPI = "AIzaSyC9rV6yesIygoVKTD6QLf_iCa9eiIIHqZ0"

[taxonomies]
  tag = "tags"
