backend:
  name: github
  repo: cruisemaniac/cruisemaniac.com_website
  # branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "static/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "date" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Featured Image", name: "image", widget: "image"}
      - { label: "Tags", name: "tags", widget: "list"}
      - { label: "Description", name: "description", widget: "string"}
  - name: "about-me"
    label: "About Page"
    folder: "content/about"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "date" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Hidden", name: "hidden", widget: "boolean"}
      - { label: "Description", name: "description", widget: "string"}
  - name: "projects-and-talks"
    label: "Projects And Talks"
    folder: "content/projects-and-talks"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "date" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Hidden", name: "hidden", widget: "boolean"}
      - { label: "Description", name: "description", widget: "string"}
  - name: "other-pages"
    label: "Other Pages"
    create: true
    folder: "content/pages"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "date" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Featured Image", name: "image", widget: "image"}
      - { label: "Tags", name: "tags", widget: "list"}
      - { label: "Description", name: "description", widget: "string"}

